BankingWebApp/Controllers/AccountUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BankingWebApp.Data;
using BankingWebApp.Models;
using Microsoft.AspNetCore.Http;

namespace BankingWebApp.Controllers
{
    public class AccountUsersController : Controller
    {
        private readonly BankingWebAppContext _context;

        public AccountUsersController(BankingWebAppContext context)
        {
            _context = context;
        }

        // GET: AccountUsers
        public async Task<IActionResult> Index()
        {
            return View(await _context.AccountUser.ToListAsync());
        }

        // GET: AccountUsers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var accountUser = await _context.AccountUser
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (accountUser == null)
            {
                return NotFound();
            }

            return View(accountUser);
        }

        // GET: AccountUsers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AccountUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,UserName,AccountNum,FirstName,LastName,Email,Mobile,Password,ConfirmPassword,Amount,Country,AccountType,PinCode,Sques,SAns,DoB")] AccountUser accountUser)
        {
            if (ModelState.IsValid)
            {
                _context.Add(accountUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(accountUser);
        }

        // GET: AccountUsers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var accountUser = await _context.AccountUser.FindAsync(id);
            if (accountUser == null)
            {
                return NotFound();
            }
            return View(accountUser);
        }

        // POST: AccountUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,UserName,AccountNum,FirstName,LastName,Email,Mobile,Password,ConfirmPassword,Amount,Country,AccountType,PinCode,Sques,SAns,DoB")] AccountUser accountUser)
        {
            if (id != accountUser.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(accountUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccountUserExists(accountUser.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(accountUser);
        }

        // GET: AccountUsers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var accountUser = await _context.AccountUser
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (accountUser == null)
            {
                return NotFound();
            }

            return View(accountUser);
        }

        // POST: AccountUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var accountUser = await _context.AccountUser.FindAsync(id);
            _context.AccountUser.Remove(accountUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AccountUserExists(int id)
        {
            return _context.AccountUser.Any(e => e.UserId == id);
        }




        public IActionResult CreateNew()
        {
            return View();
        }

        // POST: AccountUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateNew([Bind("UserId,UserName,AccountNum,FirstName,LastName,Email,Mobile,Password,ConfirmPassword,Amount,Country,AccountType,PinCode,Sques,SAns,DoB")] AccountUser accountUser)
        {
            if (ModelState.IsValid)
            {
                _context.Add(accountUser);
                Random r = new Random();
                int n = r.Next(0000, 9999);
                accountUser.AccountNum = "CDB00DF" + n.ToString();
                HttpContext.Session.SetString("AccNumber", accountUser.AccountNum);
                await _context.SaveChangesAsync();
                return RedirectToAction("SuccessNew");
            }
            return View(accountUser);
        }


        public IActionResult SuccessNew()
        {
            ViewBag.AccNum = HttpContext.Session.GetString("AccNumber");
            ViewBag.Id = HttpContext.Session.GetInt32("UserId");
            return View();
        }

    }
}

BankingWebApp/Controllers/DefaultController.cs
using BankingWebApp.Data;
using BankingWebApp.Models;
using DNTCaptcha.Core;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BankingWebApp.Controllers
{
    public class DefaultController : Controller
    {
        private readonly BankingWebAppContext _context;
        private readonly IDNTCaptchaValidatorService _validatorService;
        private readonly DNTCaptchaOptions _captchaOptions;
        public DefaultController(IDNTCaptchaValidatorService validatorService, BankingWebAppContext context, IOptions<DNTCaptchaOptions> options)
        {
            _validatorService = validatorService;
            _context = context;
            _captchaOptions = options == null ? throw new ArgumentNullException(nameof(options)) : options.Value;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult IsCustomer()
        {
            return View();
        }
        [HttpPost]
         [ValidateAntiForgeryToken]
     /*   [ValidateDNTCaptcha(
            ErrorMessage = "Please Enter Valid Captcha",
            CaptchaGeneratorLanguage = Language.English,
            CaptchaGeneratorDisplayMode = DisplayMode.ShowDigits)]*/

        public async Task<IActionResult> IsCustomer([FromForm] AccountUser u)
        {

            if (!_validatorService.HasRequestValidCaptchaEntry(Language.English, DisplayMode.ShowDigits))
            {
                this.ModelState.AddModelError(_captchaOptions.CaptchaComponent.CaptchaInputName, "Please enter the security code as a number.");
                return RedirectToAction("IsCustomer", "Default");
            }


          /*    if (ModelState.IsValid) // If `ValidateDNTCaptcha` fails, it will set a `ModelState.AddModelError`.
               {
                   //TODO: Save data
                   // return RedirectToAction(nameof(Thanks), new { name = data.Username });
               }*/
               var obj = await _context.AccountUser.Where(a => a.UserName.Equals(u.UserName)).FirstOrDefaultAsync();
               if (obj != null && obj.UserName == u.UserName && obj.Password == u.Password)
               {
                   HttpContext.Session.SetInt32("UserId", obj.UserId);
                   HttpContext.Session.SetString("UserName", obj.UserName.ToString());
                   HttpContext.Session.SetString("Balance", obj.Amount.ToString());
                   return RedirectToAction("Services");
               }

            return View();     
        }

        public ActionResult  Services()
        {
            ViewBag.Id = HttpContext.Session.GetInt32("UserId");
            ViewBag.Uname = HttpContext.Session.GetString("UserName");
            return View();
        }



        public IActionResult Forgot()
        {
            if (HttpContext.Session.GetString("UserId") != null && HttpContext.Session.GetString("FirstName") != null && HttpContext.Session.GetString("Password") != null)
            {
                return RedirectToAction("Edit","AccountUsers");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Forgot(AccountUser u)
        {
            var obj = await _context.AccountUser.Where(a => a.UserId.Equals(u.UserId)).FirstOrDefaultAsync();
            if (obj != null && obj.UserId == u.UserId && obj.FirstName == u.FirstName && obj.Sques==u.Sques && obj.SAns==u.SAns)
            {
                HttpContext.Session.SetInt32("UserId", obj.UserId);
                ViewBag.Id = HttpContext.Session.GetInt32("UserId");
               
                return RedirectToAction("Edit", "AccountUsers", new { id = ViewBag.Id });
            }

            else
            {
                ModelState.AddModelError("", "Credentials are not matched");
            }
            return View();
        }

        
    }
}

BankingWebApp/Controllers/FDsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BankingWebApp.Data;
using BankingWebApp.Models;
using Microsoft.AspNetCore.Http;

namespace BankingWebApp.Controllers
{
    public class FDsController : Controller
    {
        private readonly BankingWebAppContext _context;

        public FDsController(BankingWebAppContext context)
        {
            _context = context;
        }

        // GET: FDs
        public async Task<IActionResult> Index()
        {
            return View(await _context.FD.ToListAsync());
        }

        // GET: FDs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fD = await _context.FD
                .FirstOrDefaultAsync(m => m.FdId == id);
            if (fD == null)
            {
                return NotFound();
            }

            return View(fD);
        }

        // GET: FDs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FDs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FdId,FdInvMon,Month,UserID,FdMAmount,FdInMoney")] FD fD)
        {
            if (ModelState.IsValid)
            {
                fD.UserID=(int) HttpContext.Session.GetInt32("UserId");
               
                double m = fD.Month;
                int v = (int)m;
                HttpContext.Session.SetInt32("Tenure",v);
                double amount = fD.FdInvMon;
                if(m<6)
                {
                    fD.FdMAmount = amount + (amount * 0.04);
                }
                else if(m>=6 &&m<12)
                {
                    fD.FdMAmount = amount + (amount * 0.054);
                }

                else if (m >= 12 && m < 24)
                {
                    fD.FdMAmount = amount + (amount * 0.057);
                }

                else if (m >= 24 && m < 36)
                {
                    fD.FdMAmount = amount + (amount * 0.06);
                }

                else if (m >= 36 && m < 70)
                {
                    fD.FdMAmount = amount + (amount * 0.063);
                }
                else if (m >= 70 && m < 1200)
                {
                    fD.FdMAmount = amount + (amount * 0.07);
                }

                fD.FdInMoney = fD.FdMAmount - amount;
                int conamount = (int)fD.FdMAmount;
                int inamount = (int)fD.FdInMoney;

                HttpContext.Session.SetInt32("MAmount", conamount);
                HttpContext.Session.SetInt32("IntAmount", inamount);

                _context.Add(fD);
                await _context.SaveChangesAsync();
                //                return RedirectToAction(nameof(Index));

                return RedirectToAction("FDSuccess");
            }
            return View(fD);
        }

        // GET: FDs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fD = await _context.FD.FindAsync(id);
            if (fD == null)
            {
                return NotFound();
            }
            return View(fD);
        }

        // POST: FDs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FdId,FdInvMon,Month,UserID,FdMAmount,FdInMoney")] FD fD)
        {
            if (id != fD.FdId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fD);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FDExists(fD.FdId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fD);
        }

        // GET: FDs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fD = await _context.FD
                .FirstOrDefaultAsync(m => m.FdId == id);
            if (fD == null)
            {
                return NotFound();
            }

            return View(fD);
        }

        // POST: FDs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fD = await _context.FD.FindAsync(id);
            _context.FD.Remove(fD);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FDExists(int id)
        {
            return _context.FD.Any(e => e.FdId == id);
        }

        public IActionResult FDSuccess ()
        {
            ViewBag.Amount = HttpContext.Session.GetInt32("MAmount");
            ViewBag.IntAmount=HttpContext.Session.GetInt32("IntAmount");
            ViewBag.Month = HttpContext.Session.GetInt32("Tenure");
            return View();
        }

    }
}

BankingWebApp/Views/Default/Forgot.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model BankingWebApp.Models.AccountUser

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>AccountUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Forgot">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Sques" class="control-label"></label>
                <select name="Category" asp-for="Sques" class="form-control">
                    <option value="0">Favmovie</option>
                    <option value="1">Favbook</option>
                </select>
                <span asp-validation-for="Sques" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SAns" class="control-label"></label>
                <input asp-for="SAns" class="form-control" />
                <span asp-validation-for="SAns" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Edit" asp-controller="AccountUsers" asp-route-id="UserId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BankingWebApp/Views/Default/Services.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="bootstrap4/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.7.3/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <style>
        a:hover {
            color: red;
        }
        body {
            background-color: dimgray;
        }
    </style>


</head>
<body>
    <br />
    <br />
   

    <br>

    <div class="container">
        <h2>Welcome @ViewBag.Uname !!  Here we providing the services as below</h2>

        <div class="card-deck">

            <div class="card">
                <img class="card-img-top" src="https://s3.ap-southeast-1.amazonaws.com/com.ft.uploads/wp-content/uploads/2021/02/17142755/main-qimg-53ebd4eb9022ee0e470d4f0e62166751.png" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text"> Are you worrying by thinking about your future then dont worry we are here to help you by providing services  in form of Fd with good interest rates. Be hurry dont lose this chance. Opening a fd account is easy in our website you can just click here..</p>

                    <a asp-action="Create" asp-controller="FDs" class="btn btn-success btn-lg">
                        FixedDeposit
                        @*<span class="glyphicon glyphicon-shopping-cart"></span> Add to Cart*@
                    </a>

                </div>
            </div>


            <div class="card">
                @*   <img class="card-img-top" src="https://images.unsplash.com/photo-1519735777090-ec97162dc266?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1415&q=80" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Mad About Waves(350ml) <span class="bg-warning badge">3.5<i class="material-icons" style="font-size:10px">star</i> </span></h5>
                    <h5 class="card-title">Rs.150 <s style="font-size:12px">Rs.200</s>20%<span class="glyphicon glyphicon-exclamation-sign " style="color:red"></span></h5>

                    <p class="card-text">
                        Mad About Waves is the holistic care and styling regime dedicated to beautifying every wave type. the range is designed to tame,respect and protect the hair - embracing each unique pattern ,for breezy waves that  last
                    </p>
                    <a href="#" class="btn btn-success btn-lg">
                        <span class="glyphicon glyphicon-shopping-cart"></span> Add to Cart

                    </a>
                    <a href="#" style="text-align:right">
                        <span class="glyphicon glyphicon-heart-empty " style="font-size:20px"></span>
                    </a>
                </div>*@
            </div>

            <div class="card">
                <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgAku2NXgAkzdKiweTjGuUgVrtjIyFJtW0uGRU6jQfYPWyZGgFn2V65T0MNCJYSRqE1SQ&usqp=CAU" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">View-Profile</h5>


                    <p class="card-text">
                        You can click the below link to view your profile details
                    </p>
                    <a asp-action="Details" asp-controller="AccountUsers" asp-route-id="@ViewBag.Id" class="btn btn-success btn-lg">
                        <span class="glyphicon glyphicon-shopping-cart"></span> View-Profile

                    </a>

                </div>
            </div>

            <div class="card">
                <img class="card-img-top" src="https://img.freepik.com/free-vector/special-offer-creative-sale-banner-design_1017-16284.jpg?size=626&ext=jpg" alt="Card image cap">
                <div class="card-body">


                    <p class="card-text">
                        Very Excited Offers are waiting for you .dont miss this chance Hurry up.To check Offers click here
                    </p>
                    <a asp-action="Offers" asp-controller="Default" class="btn btn-success btn-lg">
                        Special-Offers
                    </a>

                </div>
            </div>


        </div>
        <br /> <br />


        <div class="card" style="width:250px">
            <img class="card-img-top" src="https://ittutorials.net/wp-content/uploads/reset-password.jpg" alt="Card image cap">
            <div class="card-body">

                <p class="card-text">
                    Hi User !! If you want to change your password click here!!
                </p>
                <a asp-action="Details" asp-controller="AccountUsers" asp-route-id="@ViewBag.Id" class="btn btn-success btn-lg">
                    Reset/Change Password
                </a>

            </div>
        </div>

    </div>

 

</body>
</html>